description: >
  Build training materials.
  PDF and static website.

parameters:
  training-name:
    type: string
    default: $CIRCLE_PROJECT_REPONAME
  extra-opts:
    type: string
    default: ''
  sensei-version:
    type: string
    default: latest
docker:
  - image: zenika/sensei:<< parameters.sensei-version >>
steps:
  - checkout
  - run:
      name: Generate PDF
      command: |
        /app/bin/sensei.js pdf --material . --slug << parameters.training-name >> << parameters.extra-opts >>
        mv pdf dist
  - run:
      name: Generate static site
      command: /app/bin/sensei.js build --material . --slug << parameters.training-name >> << parameters.extra-opts >>
  - persist_to_workspace:
      root: ./
      paths:
        - dist/
